### ISSUE TITLE
Kernel module rewriting

### ISSUE THREAD

**Issue by webhat** [HexHive/retrowrite#13]
I'm watching the #36c3 talk and it mentions that the kernel rewriting tool would be released in the beginning of 2020

**Comment by gannimo** [comment]
kRetroWrite was a fork of the original retrowrite and the original student graduated in February and then the world exploded. Jean-Michel is currently working on integrating the patch and writing documentation and demos. We're almost ready to release. Thanks for the patience!

**Comment by webhat** [comment]
Thanks for they reply, great research BTW!

**Comment by jeanmi151** [comment]
I finalized the integration and pushed the kernel version. You can play with it now!
Please let us know if you got any issue
