### ISSUE TITLE
can't build my binary with gcc

### ISSUE THREAD

**Issue by ghost** [HexHive/retrowrite#4]
Do you have any clue why is this happening?
...
[*] Instrumented: 3048 locations
gcc binary-basan.s -lasan -o binary-basan                                                                                                                                                      
/usr/bin/ld: /tmp/ccyZLb4w.o: in function `asan.module_ctor':
(.text+0x4b7f2): undefined reference to `__asan_init_v4'
collect2: error: ld returned 1 exit status

**Comment by sushant94** [comment]
Hey @alexandermitop, it seems like your version of gcc compiler is different from
the ones we used for testing. I'll make a proper fix by detecting this while setting up retrowrite.

In the meanwhile, you can fix this by replacing `__asan_init_v4` with just `__asan_init` in the assembly file.
